// Test Jenkinsfile to verify that the program runs as intended. This is intended for Windows

pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                cleanWs()

                withPythonEnv('python') {
                    bat "python --version"
                    bat "pip -V"
                }

                withPythonEnv('C:\\Python34\\python') {
                    bat "python --version"
                    bat "pip -V"
                }

                withPythonEnv('CPython-3.2') {
                    bat "python --version"
                    bat "pip -V"
                }

                withPythonEnv('C:\\tools\\python3\\python3') {
                    bat "python --version"
                    bat "pip -V"
                }

                withPythonEnv('C:\\tools\\python3\\python3.exe') {
                    bat "python --version"
                    bat "pip -V"
                }

                withPythonEnv('C:\\Program Files (x86)\\Jenkins\\managed_virtualenv\\') {
                    // Test for ManagedVirtualenv
                    bat "python --version"
                    bat "pip -V"
                }
            }
        }
    }
}