// Test Jenkinsfile to verify that the program runs as intended. This is intended for Linux

pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                withPythonEnv('python') {
                    sh "python --version"
                    sh "pip -V"
                }

                withPythonEnv('/usr/bin/python3') {
                    sh "python --version"
                    sh "pip -V"
                }

                withPythonEnv('CPython-3.5') {
                    sh "python --version"
                    sh "pip -V"
                }

                withPythonEnv('/var/jenkins_home/managed_virtualenv/') {
                    // Test for ManagedVirtualenv
                    sh "python --version"
                    sh "pip -V"
                }
            }
        }
    }
}